## A single prompt or response belonging to an [OasisBranch].
class_name OasisLine
extends RefCounted

const _JsonVisitor := preload("res://addons/oasis_dialogue/visitor/json_visitor.gd")

## The autogenerated key to lookup the translation for that is the actual
## text to be displayed for this line.
var key := ""

## The array of conditions that if determined true by
## [method OasisTraverserController.validate_conditions] at runtime,
## shows this line's translated [member key] to the player.
var conditions: Array[OasisKeyValue] = []

## The array of actions that are executed by
## [method OasisManager.handle_actions] at runtime if
## [b]1)[/b] this line is a prompt and is [i]shown[/i] to the player or
## [b]2)[/b] this line is a response and is [i]chosen[/i] by the player.
var actions: Array[OasisKeyValue] = []


func _init(
		key: String,
		conditions: Array[OasisKeyValue] = [],
		actions: Array[OasisKeyValue] = [],
) -> void:
	self.key = key
	self.conditions = conditions
	self.actions = actions


static func from_jsons(jsons: Array) -> Array[OasisLine]:
	var lines: Array[OasisLine] = []
	for json: Dictionary in jsons:
		var line := new(
				json[_JsonVisitor.LINE_KEY],
				OasisKeyValue.from_jsons(
					json.get(_JsonVisitor.LINE_CONDITIONS, [])
				),
				OasisKeyValue.from_jsons(
					json.get(_JsonVisitor.LINE_ACTIONS, [])
				),
		)
		lines.push_back(line)
	return lines
